import { Inter } from 'next/font/google'
import './globals.css'
import ContextProvider from './context/AuthContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Fundy',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>

        <ContextProvider>
          {children}
        </ContextProvider>

      </body>
    </html>
  )
}
